apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-service
  namespace: bookverse-prod
  labels:
    app: platform-service
    component: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
        component: platform
    spec:
      containers:
      - name: platform-aggregator
        image: apptrustswampupc.jfrog.io/bookverse-platform-internal-docker-release-local/platform:latest
        imagePullPolicy: IfNotPresent
        command: ["./entrypoint.sh", "aggregator"]
        env:
        # OIDC Authentication Configuration
        - name: OIDC_AUTHORITY
          value: "https://auth.bookverse.com"
        - name: OIDC_AUDIENCE
          value: "bookverse:api"
        - name: JWT_ALGORITHM
          value: "RS256"
        - name: AUTH_ENABLED
          value: "true"
        - name: DEVELOPMENT_MODE
          value: "false"
        # AppTrust Configuration
        - name: APPTRUST_BASE_URL
          value: "https://apptrust.jfrog.io"
        - name: APPTRUST_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: apptrust-credentials
              key: access-token
        # Platform Configuration
        - name: PLATFORM_APP_KEY
          value: "bookverse-platform"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: manifests
          mountPath: /app/manifests
      volumes:
      - name: manifests
        emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: apptrust-credentials
  namespace: bookverse-prod
  labels:
    component: platform
type: Opaque
data:
  # Base64 encoded APPTRUST_ACCESS_TOKEN
  # Replace with actual token: echo -n "your-token" | base64
  access-token: cGxhY2Vob2xkZXItdG9rZW4=
