name: Aggregate Platform Release

on:
  workflow_dispatch:
    inputs:
      write:
        description: "Create platform version and write manifest (default false uses preview only)"
        required: false
        default: "false"
  schedule:
    - cron: '0 9 */14 * 1'  # Every two weeks on Monday at 09:00 UTC

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bookverse-platform/requirements.txt

      - name: Run aggregator (preview)
        run: |
          python -m app.main --config bookverse-platform/config/services.yaml --output-dir bookverse-platform/manifests --source-stage PROD --preview
        working-directory: bookverse-platform

      - name: Create platform version and write manifest
        if: ${{ github.event.inputs.write == 'true' }}
        run: |
          python -m app.main --config bookverse-platform/config/services.yaml --output-dir bookverse-platform/manifests --source-stage PROD --write
        working-directory: bookverse-platform


