name: Aggregate Platform Release

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      write:
        description: "Create platform version and write manifest (default false runs preview only)"
        required: false
        default: false
        type: boolean

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: bookverse-platform

      - name: Export AppTrust context
        run: |
          echo "APPTRUST_BASE_URL=${{ vars.APPTRUST_BASE_URL }}" >> $GITHUB_ENV
          echo "APPTRUST_ACCESS_TOKEN=${{ secrets.APPTRUST_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Run aggregator (preview)
        if: ${{ inputs.write != true }}
        run: |
          python -m app.main --config config/services.yaml --output-dir manifests --source-stage PROD --preview
        working-directory: bookverse-platform

      - name: Create platform version and write manifest
        if: ${{ inputs.write == true }}
        run: |
          python -m app.main --config config/services.yaml --output-dir manifests --source-stage PROD
        working-directory: bookverse-platform

