name: Aggregate

on:
  # NOTE: For real environments, enable this schedule to run every second Monday at 09:00 UTC:
  # schedule:
  #   - cron: '0 9 */14 * 1'
  workflow_dispatch:
    inputs:
      write:
        description: "Create platform version and write manifest (default false runs preview only)"
        required: false
        default: false
        type: boolean

jobs:
  aggregate:
    name: Aggregate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      # Prefer canonical JFrog variables used across the repo
      JFROG_URL: ${{ vars.JFROG_URL }}
      JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
    steps:
      - name: "[Setup] Checkout"
        uses: actions/checkout@v4

      - name: "[Setup] Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: "[Setup] Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: bookverse-platform

      # AppTrust base URL is derived from JFROG_URL; admin token used for API calls
      - name: "[Setup] AppTrust context"
        run: |
          BASE="${JFROG_URL%/}"
          echo "APPTRUST_BASE_URL=${BASE}/apptrust/api/v1" >> "$GITHUB_ENV"
          echo "APPTRUST_ACCESS_TOKEN=${JFROG_ADMIN_TOKEN}" >> "$GITHUB_ENV"

      - name: "[Run] Preview aggregator"
        if: ${{ inputs.write != true }}
        run: |
          python -m app.main --config config/services.yaml --output-dir manifests --source-stage PROD --preview
        working-directory: bookverse-platform

      - name: "[Release] Create version and write manifest"
        if: ${{ inputs.write == true }}
        run: |
          python -m app.main --config config/services.yaml --output-dir manifests --source-stage PROD
        working-directory: bookverse-platform

