name: Promote

on:
  workflow_dispatch:
    inputs:
      target_stage:
        description: 'Target stage (QA, STAGING, PROD)'
        required: true
        type: choice
        options: [ QA, STAGING, PROD ]
      DEMO_MODE:
        description: 'Enable demo mode (verbose logs, request tracing)'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply DEMO_MODE settings
        if: ${{ inputs.DEMO_MODE == 'true' || env.DEMO_MODE == 'true' }}
        run: |
          echo "🔔 DEMO_MODE enabled"
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "HTTP_DEBUG_LEVEL=verbose" >> $GITHUB_ENV
          echo "BASH_XTRACE_ENABLED=1" >> $GITHUB_ENV

      - name: JFrog OIDC login
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog URL
        run: |
          jf c add --interactive=false --url "${{ vars.JFROG_URL }}" --access-token ""

      - name: Attach promotion evidence (synthetic)
        run: |
          echo "qa_summary=All critical tests passed" >> $GITHUB_ENV
          echo "approvals=2" >> $GITHUB_ENV
          echo "change_ref=DEMO-123" >> $GITHUB_ENV

      - name: Promote artifact (placeholder)
        run: |
          echo "(placeholder) promote artifact to ${{ inputs.target_stage }} with evidence"


